name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prereleaases${increment}"
      id: version
            
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
        VERSION: ${{steps.version.outputs.version}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        echo "Version released: $VERSION"
  
    - name: Build image
      env:
        VERSION: ${{steps.version.outputs.version}}
      run: |
        docker image build . -t ivanhdzrz/simple-graphql:$VERSION
    - name: Pushing image
      env:
        VERSION: ${{steps.version.outputs.version}}
      run: docker push ivanhdzrz/simple-graphql:$VERSION
        
#  - name: Build the Docker image
#   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

